library(shiny)
# library(shinyrdiversity)
library(vegan)
library(rdiversity)
#library(ggplot2)
library(ggrdiversity)
data(BCI, package = "vegan")
source("R/select_diversity.R")
source("R/whatisdiv.R")
source("R/whatisq.R")
